In [1]:
import torch

In [3]:
x = torch.randn(2, 3)
x

tensor([[ 1.8905,  0.2030,  0.4855],
        [-1.7369, -0.1918, -1.1902]])

In [11]:
y = torch.max(x, dim = 1)[0].unsqueeze(1)
y

tensor([[ 1.8905],
        [-0.1918]])

In [12]:
x - y

tensor([[ 0.0000, -1.6875, -1.4050],
        [-1.5452,  0.0000, -0.9984]])

In [14]:
z = torch.exp(x - y)
z

tensor([[1.0000, 0.1850, 0.2454],
        [0.2133, 1.0000, 0.3685]])

In [18]:
torch.sum(z, dim = 1).unsqueeze(1)

tensor([[1.4304],
        [1.5817]])

In [22]:
torch.ones(3,1)

tensor([[1.],
        [1.],
        [1.]])